#!/usr/bin/env python3
"""Generate Codex MCP worker configuration proposals from one registry.

The authoritative worker mapping lives in tools/codex-workers.json. This script
derives two proposal artifacts from it:

* tools/out/.mcp.json, a project-scope proposal for the repository root.
* tools/out/spark-apply-commands.sh, exact user-scope add/remove commands.

Option 1 dispatch is per call: each Codex call must pass model=<worker.model>
and config={"model_reasoning_effort": <worker.effort>} from the registry. MCP
server names are routing labels only; startup model/effort args are ignored by
codex mcp-server and are intentionally absent from generated .mcp.json.

The live .mcp.json is never modified. Use --check to compare the registry-derived
label-only server definitions with the live project .mcp.json and report drift
without writing. --check validates server names plus sandbox/approval/mcp-server
args only, not model selection.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "tools" / "codex-workers.json"
LIVE_MCP = ROOT / ".mcp.json"
OUT_MCP = ROOT / "tools" / "out" / ".mcp.json"
OUT_COMMANDS = ROOT / "tools" / "out" / "spark-apply-commands.sh"


def load_registry() -> dict[str, Any]:
    with REGISTRY.open(encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"{REGISTRY} must contain a JSON object")
    return data


def worker_items(registry: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    items: list[tuple[str, dict[str, Any]]] = []
    seen: set[str] = set()
    for name, worker in registry.items():
        if name.startswith("_"):
            continue
        if name in seen:
            raise ValueError(f"duplicate worker name: {name}")
        seen.add(name)
        if not isinstance(worker, dict):
            raise ValueError(f"{name} must be an object")
        for field in ("pool", "model", "effort", "status", "fallback"):
            if field not in worker:
                raise ValueError(f"{name} missing required field: {field}")
        if not isinstance(worker["fallback"], list):
            raise ValueError(f"{name} fallback must be a list")
        items.append((name, worker))
    if not items:
        raise ValueError("registry contains no workers")
    return items


def server_object() -> dict[str, Any]:
    return {
        "type": "stdio",
        "command": "codex",
        "args": [
            "-c",
            'sandbox_mode="workspace-write"',
            "-c",
            'approval_policy="never"',
            "mcp-server",
        ],
    }


def build_mcp(registry: dict[str, Any]) -> dict[str, Any]:
    servers: dict[str, Any] = {}
    for name, worker in worker_items(registry):
        servers[name] = server_object()
    return {"mcpServers": servers}


def dump_json(data: dict[str, Any]) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def command_text(mcp: dict[str, Any]) -> str:
    lines = [
        "#!/bin/sh",
        "# Proposal commands generated by tools/gen-codex-mcp.py.",
        "# Review before running. These commands update user-scope Claude MCP config.",
        "",
        "# USER-SCOPE ADD/UPDATE",
    ]
    for name, server in mcp["mcpServers"].items():
        payload = json.dumps(server, separators=(",", ":"), ensure_ascii=False)
        lines.append(f"claude mcp add-json --scope user {name} '{payload}'")
    lines.extend(["", "# ROLLBACK / REMOVAL"])
    for name in mcp["mcpServers"]:
        lines.append(f"claude mcp remove --scope user {name}")
    lines.append("git checkout -- .mcp.json")
    lines.append("")
    return "\n".join(lines)


def write_outputs(mcp: dict[str, Any]) -> None:
    OUT_MCP.parent.mkdir(parents=True, exist_ok=True)
    OUT_MCP.write_text(dump_json(mcp), encoding="utf-8")
    OUT_COMMANDS.write_text(command_text(mcp), encoding="utf-8")


def compare_server(name: str, expected: dict[str, Any], live: dict[str, Any] | None) -> list[str]:
    if live is None:
        return [f"missing server: {name}"]
    drift: list[str] = []
    for key in ("type", "command", "args"):
        if live.get(key) != expected.get(key):
            if key == "args":
                drift.append(f"wrong args for {name}: expected {expected[key]!r}, live {live.get(key)!r}")
            else:
                drift.append(f"wrong {key} for {name}: expected {expected[key]!r}, live {live.get(key)!r}")
    return drift


def check_drift(mcp: dict[str, Any]) -> int:
    if not LIVE_MCP.exists():
        print(f"DRIFT: live {LIVE_MCP} is missing")
        return 1
    with LIVE_MCP.open(encoding="utf-8") as f:
        live = json.load(f)
    live_servers = live.get("mcpServers", {})
    expected_servers = mcp["mcpServers"]
    if not isinstance(live_servers, dict):
        print("DRIFT: live .mcp.json mcpServers is missing or not an object")
        return 1

    drift: list[str] = []
    for name, expected in expected_servers.items():
        drift.extend(compare_server(name, expected, live_servers.get(name)))
    for name in live_servers:
        if name not in expected_servers:
            drift.append(f"extra server: {name}")

    if drift:
        print("DRIFT detected between tools/codex-workers.json and live .mcp.json:")
        for item in drift:
            print(f"- {item}")
        return 1
    print("OK: live .mcp.json matches tools/codex-workers.json-derived config")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift against live .mcp.json without writing")
    args = parser.parse_args(argv)

    registry = load_registry()
    mcp = build_mcp(registry)

    if args.check:
        return check_drift(mcp)

    write_outputs(mcp)
    print(command_text(mcp), end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
